### ISSUE TITLE
Rename <it> to <test>

### ISSUE THREAD

**Issue by TheJaredWilcurt** [johnsusek/vue-test-declarative#12]
I consider a 2 character, non-descriptive, variable names an anti-pattern. This becomes abundantly clear when you look at this from a semantic mark up perspective.

What is a "`<footer>`"? It is a container that goes at the end of the page.

What is a "`<nav>`"? It is a container for navigational items.

What is a "`<test>`"? It is a container for a test.

What is a "`<it>`"? I have no idea? Is it a container for a [scary clown](https://user-images.githubusercontent.com/4629794/63263452-a0aa4480-c256-11e9-9594-a36996c7918c.jpg)?

* * *

Well named functions describe what they do, and in the best scenarios can infer what arguments they accept and even what will be returned. For example: `getUserAvatar()`. Guess what it does. It gets a user's avatar. What do you think it takes as an argument? Probably a user ID. What do you think it returns? Probably a URL to that user's avatar.

What does an `it()` take in? What does an `it()` return? `¯\_(ツ)_/¯`

* * *

If you want to also support "it", I don't care, but you should use "test" as the default and recommended approach, similar to Jest.

**Comment by TheJaredWilcurt** [comment]
In the same boat, `<it will="Render message correctly">` the `will` should be renamed to something descriptive as well. `criteria`, `description`, or `title` all seem logical to me, or at least a considerable improvement over `will`.

```html
<tests for="@/components/HelloWorld.vue">
  <test title="Renders message correctly" :props="props">
    <expect text to-match="Welcome!" />
  </test>
</tests>
```

**Comment by johnsusek** [comment]
I like this idea, I named it "it" since that is the mocha function name, but you're right this isn't a great name.

I like `<test description="foo">` and will change it to this soon

**Comment by johnsusek** [comment]
This is complete and part of the 1.0 release! Ended up going with `<test name="foo">`
